# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: request_tracking_db
    ports:
      - "3305:3306"